const mongoose = require('mongoose');

const PostSchema = new mongoose.Schema({
    user:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    text:{
        type:String,
        required:true
    },
    name:{
        type:String
    },
    avatar:{
        type:String
    },
    date:{
        type:Date,
        default:Date.now
    },
    likes:[
        {
            user:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'users'
            },
            name:{
                type:String
            }
        }
    ],
    comments:[
        {
            user:{
                type:mongoose.Schema.Types.ObjectId,
                ref:'users'
            },
            text:{
                type:String,
                required:true
            },
            name:{
                type:String
            },
            avatar:{
                type:String
            },
            date:{
                type:Date,
                default:Date.now
            },
            likes:[
                {
                    user:{
                        type:mongoose.Schema.Types.ObjectId,
                        ref:'users'
                    },
                    name:{
                        type:String
                    }
                }
            ]

        }
    ]
})
module.exports= Post = mongoose.model('post',PostSchema);